service: trigger-dynamo

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true

functions:
  hero-insert:
    handler: handler.heroesInsert
    events:
      - httpApi:
          path: /heroes
          method: post
